-- Business interface master record + immutable JSON version snapshots.

CREATE TABLE interface_definition (
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          varchar(64) NOT NULL,
    environment_id     bigint      NOT NULL,
    application_id     bigint      NOT NULL,
    interface_no       varchar(64) NOT NULL,
    template_id        bigint,
    status             varchar(32) NOT NULL,
    current_version    varchar(32) NOT NULL,
    current_version_id bigint,
    created_at         timestamp with time zone NOT NULL,
    updated_at         timestamp with time zone NOT NULL,
    CONSTRAINT uk_interface_tenant_env_no UNIQUE (tenant_id, environment_id, interface_no)
);

CREATE INDEX ix_interface_scope ON interface_definition (tenant_id, environment_id, application_id);

CREATE TABLE interface_version (
    id                       bigint generated by default as identity PRIMARY KEY,
    tenant_id                varchar(64) NOT NULL,
    interface_definition_id  bigint      NOT NULL,
    version                  varchar(32) NOT NULL,
    change_type              varchar(16) NOT NULL,
    change_summary           varchar(1024),
    content_json             text        NOT NULL,
    source_environment_id    bigint,
    source_version           varchar(32),
    created_at               timestamp with time zone NOT NULL,
    updated_at               timestamp with time zone NOT NULL,
    CONSTRAINT uk_interface_version UNIQUE (interface_definition_id, version)
);

CREATE INDEX ix_interface_version_def ON interface_version (tenant_id, interface_definition_id, id);
