-- Interface template master record + immutable JSON version snapshots.

CREATE TABLE interface_template (
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          varchar(64)  NOT NULL,
    environment_id     bigint       NOT NULL,
    application_id     bigint       NOT NULL,
    code               varchar(128) NOT NULL,
    status             varchar(32)  NOT NULL,
    current_version    varchar(32)  NOT NULL,
    current_version_id bigint,
    created_at         timestamp with time zone NOT NULL,
    updated_at         timestamp with time zone NOT NULL,
    CONSTRAINT uk_template_scope_code UNIQUE (tenant_id, environment_id, application_id, code)
);

CREATE INDEX ix_template_scope ON interface_template (tenant_id, environment_id, application_id);

CREATE TABLE template_version (
    id                    bigint generated by default as identity PRIMARY KEY,
    tenant_id             varchar(64) NOT NULL,
    interface_template_id bigint      NOT NULL,
    version               varchar(32) NOT NULL,
    change_type           varchar(16) NOT NULL,
    change_summary        varchar(1024),
    content_json          text        NOT NULL,
    source_environment_id bigint,
    source_version        varchar(32),
    created_at            timestamp with time zone NOT NULL,
    updated_at            timestamp with time zone NOT NULL,
    CONSTRAINT uk_template_version UNIQUE (interface_template_id, version)
);

CREATE INDEX ix_template_version_template ON template_version (tenant_id, interface_template_id, id);
