-- Tenant, environment and application scope for the DCC data contract center.
-- First migration above the baseline (20260901000000); see
-- docs/flyway/script-naming-convention.md.

CREATE TABLE tenant (
    id          bigint generated by default as identity PRIMARY KEY,
    code        varchar(64)  NOT NULL,
    name        varchar(128) NOT NULL,
    description varchar(512),
    enabled     boolean      NOT NULL DEFAULT true,
    created_at  timestamp with time zone NOT NULL,
    updated_at  timestamp with time zone NOT NULL,
    CONSTRAINT uk_tenant_code UNIQUE (code)
);

CREATE TABLE tenant_environment (
    id          bigint generated by default as identity PRIMARY KEY,
    tenant_id   varchar(64)  NOT NULL,
    code        varchar(32)  NOT NULL,
    name        varchar(128) NOT NULL,
    description varchar(512),
    sort_order  integer      NOT NULL,
    created_at  timestamp with time zone NOT NULL,
    updated_at  timestamp with time zone NOT NULL,
    CONSTRAINT uk_env_tenant_code UNIQUE (tenant_id, code)
);

CREATE TABLE tenant_application (
    id          bigint generated by default as identity PRIMARY KEY,
    tenant_id   varchar(64)  NOT NULL,
    code        varchar(64)  NOT NULL,
    name        varchar(128) NOT NULL,
    description varchar(512),
    created_at  timestamp with time zone NOT NULL,
    updated_at  timestamp with time zone NOT NULL,
    CONSTRAINT uk_app_tenant_code UNIQUE (tenant_id, code)
);
