-- Recorded artifact -> data standard references (delete-guard + "where used").

CREATE TABLE standard_reference (
    id              bigint generated by default as identity PRIMARY KEY,
    tenant_id       varchar(64)  NOT NULL,
    standard_id     bigint       NOT NULL,
    ref_type        varchar(32)  NOT NULL,
    ref_object_id   bigint       NOT NULL,
    ref_object_code varchar(128),
    created_at      timestamp with time zone NOT NULL,
    updated_at      timestamp with time zone NOT NULL,
    CONSTRAINT uk_standard_reference UNIQUE (tenant_id, ref_type, ref_object_id, standard_id)
);

CREATE INDEX ix_standard_reference_standard ON standard_reference (tenant_id, standard_id);
