-- Data standard (数标) master record + immutable version snapshots.

CREATE TABLE data_standard (
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          varchar(64)  NOT NULL,
    environment_id     bigint       NOT NULL,
    application_id     bigint       NOT NULL,
    code               varchar(128) NOT NULL,
    category           varchar(64),
    status             varchar(32)  NOT NULL,
    current_version    varchar(32)  NOT NULL,
    current_version_id bigint,
    created_at         timestamp with time zone NOT NULL,
    updated_at         timestamp with time zone NOT NULL,
    CONSTRAINT uk_standard_scope_code UNIQUE (tenant_id, environment_id, application_id, code)
);

CREATE INDEX ix_standard_scope ON data_standard (tenant_id, environment_id, application_id);
CREATE INDEX ix_standard_category ON data_standard (tenant_id, category);

CREATE TABLE data_standard_version (
    id                   bigint generated by default as identity PRIMARY KEY,
    tenant_id            varchar(64)  NOT NULL,
    standard_id          bigint       NOT NULL,
    version              varchar(32)  NOT NULL,
    change_type          varchar(16)  NOT NULL,
    change_summary       varchar(1024),
    name                 varchar(256) NOT NULL,
    description          varchar(1024),
    data_type            varchar(64)  NOT NULL,
    length               integer,
    scale                integer,
    required             boolean      NOT NULL,
    default_value        varchar(256),
    enum_values          varchar(1024),
    regex                varchar(512),
    example_value        varchar(512),
    source_environment_id bigint,
    source_version       varchar(32),
    created_at           timestamp with time zone NOT NULL,
    updated_at           timestamp with time zone NOT NULL,
    CONSTRAINT uk_standard_version UNIQUE (standard_id, version)
);

CREATE INDEX ix_standard_version_standard ON data_standard_version (tenant_id, standard_id, id);
