-- Table structure master record + immutable JSON version snapshots.

CREATE TABLE table_structure (
    id                 bigint generated by default as identity PRIMARY KEY,
    tenant_id          varchar(64)  NOT NULL,
    environment_id     bigint       NOT NULL,
    application_id     bigint       NOT NULL,
    code               varchar(128) NOT NULL,
    status             varchar(32)  NOT NULL,
    current_version    varchar(32)  NOT NULL,
    current_version_id bigint,
    created_at         timestamp with time zone NOT NULL,
    updated_at         timestamp with time zone NOT NULL,
    CONSTRAINT uk_table_scope_code UNIQUE (tenant_id, environment_id, application_id, code)
);

CREATE INDEX ix_table_scope ON table_structure (tenant_id, environment_id, application_id);

CREATE TABLE table_structure_version (
    id                    bigint generated by default as identity PRIMARY KEY,
    tenant_id             varchar(64)  NOT NULL,
    table_structure_id    bigint       NOT NULL,
    version               varchar(32)  NOT NULL,
    change_type           varchar(16)  NOT NULL,
    change_summary        varchar(1024),
    content_json          text         NOT NULL,
    source_environment_id bigint,
    source_version        varchar(32),
    created_at            timestamp with time zone NOT NULL,
    updated_at            timestamp with time zone NOT NULL,
    CONSTRAINT uk_table_version UNIQUE (table_structure_id, version)
);

CREATE INDEX ix_table_version_structure ON table_structure_version (tenant_id, table_structure_id, id);
