-- Environment migration orders (with approval) + direct-maintenance provenance.

CREATE TABLE migration_order (
    id                     bigint generated by default as identity PRIMARY KEY,
    tenant_id              varchar(64) NOT NULL,
    source_environment_id  bigint      NOT NULL,
    target_environment_id  bigint      NOT NULL,
    artifact_type          varchar(32) NOT NULL,
    artifact_id            bigint      NOT NULL,
    artifact_code          varchar(128),
    source_version         varchar(32),
    status                 varchar(32) NOT NULL,
    note                   varchar(512),
    target_artifact_id     bigint,
    target_version         varchar(32),
    previous_target_version varchar(32),
    created_at             timestamp with time zone NOT NULL,
    updated_at             timestamp with time zone NOT NULL
);

CREATE INDEX ix_migration_scope ON migration_order (tenant_id, target_environment_id, status);
CREATE INDEX ix_migration_artifact ON migration_order (tenant_id, artifact_type, artifact_id);
