spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_HOST_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_HOST_PORT}
      password: ${REDIS_PASSWORD}
